name: PR Pipeline

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, edited]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests and collect coverage
        run: npm run test:coverage

      - name: Upload unit test coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-coverage
          path: coverage/
          retention-days: 1

  e2e-test:
    name: E2E Test
    runs-on: ubuntu-latest
    needs: lint
    environment: integration

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Start Astro Dev Server and Wait
        env:
          PORT: 4321
        run: |
          npm run dev -- --port $PORT &> astro_dev.log &
          echo "Waiting for Astro dev server to be ready on http://localhost:$PORT..."
          npx wait-on http://localhost:$PORT --timeout 120000
          echo "Astro dev server is ready!"

      - name: Display Astro Dev Server Logs
        if: always()
        run: |
          echo "--- Astro Dev Server Logs ---"
          cat astro_dev.log || echo "astro_dev.log not found or empty"
          echo "-----------------------------"

      - name: Install Playwright browser Chromium
        run: npx playwright install --with-deps chromium

      - name: Run E2E Tests and collect coverage
        run: npx playwright test --project=chromium --grep-invert @visual
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          E2E_USERNAME_ID: ${{ secrets.E2E_USERNAME_ID }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
          PLAYWRIGHT_TEST_BASE_URL: http://localhost:4321

      - name: Upload E2E test coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-coverage
          path: playwright-report/
          retention-days: 1

  status-comment:
    name: Update PR Status
    runs-on: ubuntu-latest
    needs: [lint, unit-test, e2e-test]
    if: success()

    steps:
      - name: Download all coverage reports
        uses: actions/download-artifact@v4
        with:
          path: coverage-reports

      - name: Post status comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ✅ All checks passed! Unit tests, E2E tests, and linting were successful. 

            Coverage reports have been generated and are available as artifacts.
